#!/bin/sh

if [ -z "$API_KEY" ] || [ -z "$API_SECRET" ]
then
   export API_KEY=45250532
   export API_SECRET='54afc8f4b42cbec283a979313eea14ea398fb221'
fi

if [ -d "storage" ]
then
  rm -rf storage/
fi

php -S 0.0.0.0:8080 -t web web/index.php
